export enum TemplateType {
    Component = 'component.tmpl',
    ConponentSpec = 'component.spec.tmpl',
    ComponentHtml = 'component.html.tmpl',
    ComponentStyle = 'component.style.tmpl',
    Directive = 'directive.tmpl',
    DirectiveSpec = 'directive.spec.tmpl',
    Module = 'module.tmpl',
    ModuleRouting = 'module.routing.tmpl',
    Pipe = 'pipe.tmpl',
    PipeSpec = 'pipe.spec.tmpl',
    Service = 'service.tmpl',
    ServiceNg6 = 'service.ng6.tmpl',
    ServiceSpec = 'service.spec.tmpl',
    Class = 'class.tmpl',
    ClassSpec = 'class.spec.tmpl',
    Enum = 'enum.tmpl',
    Inteface = 'interface.tmpl',
    Route = 'route.tmpl',
    
    AerionProject = 'aerionProject.tmpl',
    AerionProjectSpec = 'aerionProject.spec.tmpl',
    AerionProjectHtml = 'aerionProject.html.tmpl',
    AerionProjectStyle = 'aerionProject.style.tmpl',
    AerionProjectStroreActionSpec = 'aerionProject.action.spec.ts',
    AerionProjectStoreActionts = 'aerionProject.action.ts',
    AerionProjectStroreReducerSpec = 'aerionProject.action.spec.ts',
    AerionProjectStoreReducerts = 'aerionProject.action.ts',
    AerionProjectStroreEffectSpec = 'aerionProject.action.spec.ts',
    AerionProjectStoreEffectts = 'aerionProject.action.ts',
    AerionProjectStoreInterface = 'aerionProject.action.spec.ts',
}
